_BASE_: "./Base-RCNN-FPN.yaml"


MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
#  WEIGHTS: "/home/kmj21/code/detectron2_new/tools/output/model_final.pth"
  WEIGHTS: "/home/kmj21/code/detectron2_new/tools/output/namu_new_20220311/model_0269999.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 1024
#    NUM_CLASSES:  38
    NUM_CLASSES:  3


DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  BASE_LR: 0.0025
  IMS_PER_BATCH: 10
  STEPS: (210000, 250000)
  MAX_ITER: 270000
#  STEPS: (1000, 3000)
#  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 10000


#OUTPUT_DIR: "/home/kmj21/code/detectron2_new/tools/output"

INPUT:
  FORMAT: "BGR"
#  FORMAT: "gray_16bits"

DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)


#TEST:
#  EVAL_PERIOD: 10000
